### ISSUE TITLE
different text size of the watch for different panels?

### ISSUE THREAD

**Issue by ser** [nwg-piotr/nwg-menu#21]
it's unfortunately not clear, how can i change size for watch to have it different on different panels (monitors)?

thanks!

**Comment by nwg-piotr** [comment]
Use a different CSS ID (other than #clock) in another css file.

![obraz](https://github.com/nwg-piotr/nwg-menu/assets/20579136/d4903347-7bbc-43b0-85b3-b76012d60ef4)
