### ISSUE TITLE
nwg-menu with waybar?

### ISSUE THREAD

**Issue by ser** [nwg-piotr/nwg-menu#22]
What's the recommended way to have nwg-menu available on waybar?

**Comment by nwg-piotr** [comment]
Haven't used waybar for years, but I'm pretty sure one can add a button there. For menu positioning, `nwg-menu -h` is your friend.

**Comment by ser** [comment]
What I have is:

```
    "custom/nwg-menu": {
      "format": "MENU",
      "on-click": "nwg-menu",
      "tooltip": false,
    },
```

and it shows up correctly, let me choose a program to run, but does not run in and just prints what should be run on the terminal :)

**Comment by nwg-piotr** [comment]
Could you try `nwg-menu -wm hyprland` or `nwg-menu -wm sway`, depending on what compositor you are on?

**Comment by ser** [comment]
BINGO!

```
    "custom/nwg-menu": {
      "format": "MENU",
      "on-click": "nwg-menu -wm hyprland",
      "tooltip": false,
    },
```

works like a charm, thanks for explanation!

**Comment by nwg-piotr** [comment]
Can't look at the code at the moment, but the compositor should have been auto-detected, if I remember well. I'm not sure what goes wrong on your side. Or maybe I'm wrong. I don't use nwg-menu in real life.

**Comment by ser** [comment]
The most important is that it works now :)
