### ISSUE TITLE
[Bug] Build error at gotk3/gdk: 'undefined: callback' - needs an upgrade to v0.6.4.1

### ISSUE THREAD

**Issue by tkapias** [nwg-piotr/nwg-menu#23]
I had this error when building on a Debian/testing with go 1.22:

``` bash
# github.com/gotk3/gotk3/gdk
../../../../go/pkg/mod/github.com/gotk3/gotk3@v0.6.4/gdk/gdk_since_3_22.go:140:180: undefined: callback
make: *** [Makefile:13 : build] Erreur 1
```

The same issue with a solution is explained in this gotk3 thread: 

  - [gotk3/gotk3 issue 932](https://github.com/gotk3/gotk3/issues/932#issuecomment-2247569425)

There is a fix in tag v0.6.4.1. The version needs to be specified because latest is still v0.6.4 and does not work.

**Comment by nwg-piotr** [comment]
I'll fix tonight,
