### ISSUE TITLE
Ghost entry in favorites

### ISSUE THREAD

**Issue by washikano** [nwg-piotr/nwg-menu#24]
OS: Arch Linux
Kernel: Linux 6.10.10-arch1-1
WM: hyprland 0.43.0-1
Package ver.: nwg-menu 0.1.4-1

If a launcher for a package was pinned to favorites, but that package was uninstalled before unpinning from favorites, then a ghost entry for that package will remain pinned as a blank space. Unpinning via right-click will only remove it temporarily; if the launcher is invoked again, then the ghost entry will come back.

Steps to reproduce:
1. Install any package that includes a .desktop entry
2. Open nwg-menu, pin the package to favorites, then close nwg-menu
3. Uninstall said package
4. Open nwg-menu again; the ghost entry should appear

To get rid of the ghost entry, re-install the package, unpin it from nwg-menu, then uninstall again.

**Comment by nwg-piotr** [comment]
It doesn't behave like this on my side. Tried with emacs. If I pin emacs and then uninstall it, the pinned item no longer appears, until I install emacs back.

**Comment by washikano** [comment]
https://github.com/user-attachments/assets/6b64b4eb-846e-4617-bebd-3e0906d9d385

**Comment by washikano** [comment]
Sorry, I should've been clearer. By ghost entry I meant a blank space where the previously pinned entry would've been.

**Comment by nwg-piotr** [comment]
OK, got it. I'll add a check if the DesktopID actually exists.

**Comment by nwg-piotr** [comment]
I've also added some lines to check and remove non-existent items while saving pinned cache.
