### ISSUE TITLE
When placing the menu top, can favorites and application categories be flipped?

### ISSUE THREAD

**Issue by rharmonson** [nwg-piotr/nwg-menu#26]
Skip to https://github.com/nwg-piotr/nwg-menu/issues/26#issuecomment-2365227301. The initial posts are me figuring stuff out.
---
On initial launch, nwg-menu size is pretty good but on selecting an application category, the window shrinks and I must use the slider.

My feeling is the this can be set in the css, but my experimentation hasn't been very fruitful. Using list, I can set a min height but the categories are push to the bottom--I have the menu top-left. Attempts to set for the window height and minimum height in the css doesn't appear to have any effect.

I am sure that I am doing some wrong and appreciate your guidance.

Screen shots attached.
![nwg-menu-onlaunch](https://github.com/user-attachments/assets/ee03d8ca-2142-402e-9f93-0bbbded51b0c)
![nwg-menu-oncatselect](https://github.com/user-attachments/assets/06827327-473b-4c83-8c3e-5f68b109c3c0)
![nwg-menu-longlist](https://github.com/user-attachments/assets/2b952b90-730b-4d49-b093-56fa22338f6f)

**Comment by rharmonson** [comment]
Example of using min-height (list) that would do the trick if I could get the list to align top under the search box.
![nwg-menu-list_min-height](https://github.com/user-attachments/assets/9b0a6d33-5b31-46bb-b142-9032685f27b6)

I will keep at it.

**Comment by rharmonson** [comment]
Alright, I now understand how you have this setup. You have a div or box for the user to add favorites which is above the categories of software. Your current format makes complete sense if it is used on the bottom of the screen. To use the menu from the top, the two would need to be flipped with categories top and favorites bottom.

Is this possible?

**Comment by nwg-piotr** [comment]
Like this?

![obraz](https://github.com/user-attachments/assets/de643a97-6ac0-4079-b774-d97fe1b44d1b)

Yes, it would be a cosmetic change.

**Comment by rharmonson** [comment]
That would do it. Thank you!

Gentoo's nwg-menu testing package is version 1.3.0. I am going to have to create patches from your commits and hope the dependencies are met to build.

Nice menu and I will close the issue. Again, thank you.

**Comment by nwg-piotr** [comment]
Don't hurry. I'm back-porting some other forgotten stuff right now.

**Comment by nwg-piotr** [comment]
Done.
